# site settings
title: TIS Lab
logo: images/logo.svg

# page defaults
description: Translational and Integrative Sciences Lab
header: images/bg-dna.jpg
footer: images/bg-dna.jpg

# site nav bar
nav:
  - link: research
    tooltip: Published works
  - link: tools
    tooltip: Tools, datasets, and more
  - link: team
    tooltip: About our team
  - link: education
    tooltip: Teaching and educational materials
  - link: contact
    tooltip: Email, address, and location

# site social media
email: info@tislabs.org
google-scholar: Melissa Haendel
github: tis-lab
twitter: ontowonka

# base directory where site is hosted
baseurl: /tislab.org-new

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
