# site properties and page defaults
title: 上海交通大学智能媒体与创意实验室
# subtitle: 
description: 致力于成为生成式AI在媒体领域（图像、视频、三维、交互式媒体）核心引擎的缔造者，专注于突破高可控媒体生成的极限。
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@JfanLiu.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: JfanLiu
  twitter: JfanLiu
  youtube: JfanLiu

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
